version: '3'

services:
  simulator:
    build: .
    volumes:
      # Mount the current directory to /app in the container
      # This allows for easy development without rebuilding the image
      - .:/app
    environment:
      # Set log level
      - LOG_LEVEL=INFO
    # Keep the container running
    tty: true
    # You can override the default command here
    # command: python multi_pump_controller.py